name: publish

on:
  push:
    tags:
      - 'v*'

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install Dependencies
        run: pnpm install

      - name: Run linter
        run: pnpm run lint

  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install Dependencies
        run: pnpm install

      - name: Run vitest
        run: pnpm run test

  build:
    name: Builds source into JavaScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install Dependencies
        run: pnpm install

      - name: Run build
        run: pnpm run build

  publish_dry_run:
    name: Publish command on dry run
    runs-on: ubuntu-latest
    needs: [build, test, lint]
    env:
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Set Auth Token for NPM Registry
        run: pnpm config set //registry.npmjs.org/:_authToken ${NODE_AUTH_TOKEN}

      - name: Publish
        run: pnpm publish --dry-run --registry=https://registry.npmjs.org/ --no-git-checks

  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    needs: [publish_dry_run]
    env:
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Set Auth Token for NPM Registry
        run: pnpm config set //registry.npmjs.org/:_authToken ${NODE_AUTH_TOKEN}

      - name: Publish
        run: pnpm publish --access public --registry=https://registry.npmjs.org/ --no-git-checks

  create-release:
    name: Create a release
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Create Release Notes
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.request(`POST /repos/${{ github.repository }}/releases`, {
              tag_name: "${{ github.ref }}",
              generate_release_notes: true
            });
